---
- name: Configure the Nginx (Stable) PPA
  apt_repository: repo=ppa:nginx/stable state=present

- name: Install Nginx
  apt: pkg=nginx={{ nginx_version }} state=present

- name: Delete default site
  file: path=/etc/nginx/sites-enabled/default state=absent
  when: nginx_delete_default_site | bool
  notify:
    - Restart Nginx

- name: Configure Nginx
  template: src=nginx.conf.j2 dest=/etc/nginx/nginx.conf
  notify:
    - Restart Nginx
